// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	ID               *string  `json:",omitempty"`
	Name             *string  `json:",omitempty"`
	Dataset          *string  `json:",omitempty"`
	Description      *string  `json:",omitempty"`
	TimePeriod       *int     `json:",omitempty"`
	TargetPercentage *float64 `json:",omitempty"`
	SLI              *string  `json:",omitempty"`
	Tags             []Tag    `json:",omitempty"`
}

// Tag is autogenerated from the json schema
type Tag struct {
	Key   *string `json:",omitempty"`
	Value *string `json:",omitempty"`
}
