AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Creates a CloudWatch Metrics Stream to Honeycomb.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          Default: Required Parameters
        Parameters:
          - HoneycombAPIKey
          - S3FailureBucketArn
      - Label:
          Default: "Optional: Metric Filtering"
        Parameters:
          - MetricFilterMethod
          - FilterNamespace
          - FilterNamespace1
          - FilterNamespace2
          - FilterNamespace3
      - Label:
          Default: Optional Parameters
        Parameters:
          - HoneycombAPIHost
          - HoneycombDataset
          - HttpBufferingInterval
          - HttpBufferingSize
          - KinesisFirehoseArn
          - S3BackupMode
          - S3BufferingInterval
          - S3BufferingSize

Parameters:
  HoneycombAPIKey:
    Type: String
    NoEcho: true
    Description: Your Honeycomb Team's API key.
  HoneycombDataset:
    Type: String
    Default: cloudwatch-metrics
    Description: The target Honeycomb dataset for the Stream to publish to.
  HoneycombAPIHost:
    Type: String
    Default: https://api.honeycomb.io
    Description: Optional. Override the default Honeycomb API host.
  MetricFilterMethod:
    Type: String
    Default: Include
    Description: >-
      The stream can be filtered by namespace (e.g. 'AWS/Lambda', 'AWS/EC2').
      Select "Include" for an inclusion filter or "Exclude" for an exclusion filter.
      Set up to four namespaces for the filter to target below.
    AllowedValues:
      - Include
      - Exclude
  FilterNamespace:
    Type: String
    Default: ""
    Description: A namespace to use for filtering metrics from the stream. Leave blank if you do not need to filter by namespace.
  FilterNamespace1:
    Type: String
    Default: ""
    Description: A namespace to use for filtering metrics from the stream. Leave blank if you do not need to filter by namespace.
  FilterNamespace2:
    Type: String
    Default: ""
    Description: A namespace to use for filtering metrics from the stream. Leave blank if you do not need to filter by namespace.
  FilterNamespace3:
    Type: String
    Default: ""
    Description: A namespace to use for filtering metrics from the stream. Leave blank if you do not need to filter by namespace.
  HttpBufferingInterval:
    Type: Number
    Default: 60
    Description: The Kinesis Firehose http buffer interval, in seconds.
    MinValue: 60
    MaxValue: 900
  HttpBufferingSize:
    Type: Number
    Default: 15
    Description: The Kinesis Firehose http buffer size, in MiB.
    MinValue: 1
    MaxValue: 128
  KinesisFirehoseArn:
    Type: String
    Default: ""
    Description: >-
      By default, a Kinesis Firehose Delivery Stream will be created.
      You can override this behaviour by providing an Arn of an existing Firehose Delivery Stream.
    ConstraintDescription: The Arn of an existing Kinesis Firehose Delivery Stream.
  S3BackupMode:
    Type: String
    Default: FailedDataOnly
    Description: Should we only backup to S3 data that failed delivery, or all data?
    AllowedValues:
      - AllData
      - FailedDataOnly
  S3FailureBucketArn:
    Type: String
    Description: The ARN of the S3 Bucket that will store any events that failed to be sent to Honeycomb.
    ConstraintDescription: The ARN of a S3 Bucket.
  S3BufferingInterval:
    Type: Number
    Default: 400
    Description: The Kinesis Firehose S3 buffer interval, in seconds.
    MinValue: 60
    MaxValue: 900
  S3BufferingSize:
    Type: Number
    Default: 10
    Description: The Kinesis Firehose S3 buffer size, in MiB.
    MinValue: 1
    MaxValue: 128

Conditions:
  CreateKinesisFirehose: !Equals [!Ref KinesisFirehoseArn, ""]
  EnableIncludeNamespace:
    !And [
      !Not [!Equals [!Ref FilterNamespace, ""]],
      !Equals [!Ref MetricFilterMethod, "Include"],
    ]
  EnableIncludeNamespace1:
    !And [
      !Not [!Equals [!Ref FilterNamespace1, ""]],
      !Equals [!Ref MetricFilterMethod, "Include"],
    ]
  EnableIncludeNamespace2:
    !And [
      !Not [!Equals [!Ref FilterNamespace2, ""]],
      !Equals [!Ref MetricFilterMethod, "Include"],
    ]
  EnableIncludeNamespace3:
    !And [
      !Not [!Equals [!Ref FilterNamespace3, ""]],
      !Equals [!Ref MetricFilterMethod, "Include"],
    ]
  EnableExcludeNamespace:
    !And [
      !Not [!Equals [!Ref FilterNamespace, ""]],
      !Equals [!Ref MetricFilterMethod, "Exclude"],
    ]
  EnableExcludeNamespace1:
    !And [
      !Not [!Equals [!Ref FilterNamespace1, ""]],
      !Equals [!Ref MetricFilterMethod, "Exclude"],
    ]
  EnableExcludeNamespace2:
    !And [
      !Not [!Equals [!Ref FilterNamespace2, ""]],
      !Equals [!Ref MetricFilterMethod, "Exclude"],
    ]
  EnableExcludeNamespace3:
    !And [
      !Not [!Equals [!Ref FilterNamespace3, ""]],
      !Equals [!Ref MetricFilterMethod, "Exclude"],
    ]

Resources:
  KinesisToHoneycombStack:
    Type: AWS::CloudFormation::Stack
    Condition: CreateKinesisFirehose
    Properties:
      TemplateURL: https://honeycomb-builds.s3.amazonaws.com/cloudformation-templates/latest/kinesis-firehose.yml
      Parameters:
        Name: !Sub "${AWS::StackName}"
        HoneycombAPIKey: !Ref HoneycombAPIKey
        HoneycombDataset: !Ref HoneycombDataset
        S3FailureBucketArn: !Ref S3FailureBucketArn
        HoneycombAPIHost: !Ref HoneycombAPIHost
        HttpBufferingInterval: !Ref HttpBufferingInterval
        HttpBufferingSize: !Ref HttpBufferingSize
        S3BackupMode: !Ref S3BackupMode
        S3BufferingInterval: !Ref S3BufferingInterval
        S3BufferingSize: !Ref S3BufferingSize
  HoneycombMetricStreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - streams.metrics.cloudwatch.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub "hnystream-${AWS::StackName}"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "firehose:PutRecord"
                  - "firehose:PutRecordBatch"
                Resource: !If
                  - CreateKinesisFirehose
                  - !GetAtt KinesisToHoneycombStack.Outputs.KinesisDeliveryStreamArn
                  - Ref: KinesisFirehoseArn
  HoneycombCWLStream:
    Type: AWS::CloudWatch::MetricStream
    Properties:
      Name: !Sub "honeycomb-metric-stream-${AWS::StackName}"
      OutputFormat: opentelemetry0.7
      RoleArn: !GetAtt HoneycombMetricStreamRole.Arn
      FirehoseArn: !If
        - CreateKinesisFirehose
        - !GetAtt KinesisToHoneycombStack.Outputs.KinesisDeliveryStreamArn
        - Ref: KinesisFirehoseArn
      IncludeFilters:
        - !If
          - EnableIncludeNamespace
          - Namespace: !Ref FilterNamespace
          - !Ref "AWS::NoValue"
        - !If
          - EnableIncludeNamespace1
          - Namespace: !Ref FilterNamespace1
          - !Ref "AWS::NoValue"
        - !If
          - EnableIncludeNamespace2
          - Namespace: !Ref FilterNamespace2
          - !Ref "AWS::NoValue"
        - !If
          - EnableIncludeNamespace3
          - Namespace: !Ref FilterNamespace3
          - !Ref "AWS::NoValue"
      ExcludeFilters:
        - !If
          - EnableExcludeNamespace
          - Namespace: !Ref FilterNamespace
          - !Ref "AWS::NoValue"
        - !If
          - EnableExcludeNamespace1
          - Namespace: !Ref FilterNamespace1
          - !Ref "AWS::NoValue"
        - !If
          - EnableExcludeNamespace2
          - Namespace: !Ref FilterNamespace2
          - !Ref "AWS::NoValue"
        - !If
          - EnableExcludeNamespace3
          - Namespace: !Ref FilterNamespace3
          - !Ref "AWS::NoValue"

Outputs:
  KinesisDeliveryStreamArn:
    Description: The ARN of the Firehose Delivery Stream
    Value: !If
      - CreateKinesisFirehose
      - !GetAtt KinesisToHoneycombStack.Outputs.KinesisDeliveryStreamArn
      - Ref: KinesisFirehoseArn
  MetricStreamArn:
    Description: The ARN of the Metric Stream
    Value: !GetAtt HoneycombCWLStream.Arn
  MetricStreamIAMRoleArn:
    Description: The ARN of IAM Role created for the Metric Stream
    Value: !GetAtt HoneycombMetricStreamRole.Arn
