name: Publish Cloudformation Templates

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.md
      - CHANGELOG.md

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  publish-templates:
    name: Publish CloudFormation Templates
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          aws-region: us-east-1

      - name: Publish Templates - PRs
        id: publish_prs
        run: make publish-templates folder=prs version=$PR_NUMBER
        if: github.event_name == 'pull_request'

      - name: Sync Templates - Latest
        id: publish_latest
        run: make publish-templates folder=latest
        if: github.event_name == 'push'
