name: Validate and Lint Cloudformation Templates

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md

jobs:
  validate-templates:
    name: Validate CloudFormation Templates
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          role-duration-seconds: 900 # 15min - lowest possible value

      - name: Validate Templates
        id: validate
        run: make validate-templates

  lint-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
        with:
          args: "templates/*.yml"
